name: Lambda Despliegue

on:
  push:
    branches:
      - main  # Ejecutar el pipeline al hacer push en la rama "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Clona el repositorio desde GitHub

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: |
        sudo apt-get install -y zip  # Asegúrate de que `zip` esté instalado

    - name: Package Lambda function
      run: |
        zip -j lambda_function.zip index.py  # Empaqueta index.py en un archivo ZIP

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name GestionPedidos \  # Nombre exacto de tu función Lambda en AWS
          --zip-file fileb://lambda_function.zip
